version: '2'
services:
  card-service:
    image: card-service:latest
    ports:
      - 8081:8081
    environment:
      - APP_SLEEP=30
  player-service:
    image: player-service:latest
    ports:
      - 8082:8082
    environment:
      - APP_SLEEP=30
  game-service:
    image: game-service:latest
    ports:
    - 8083:8083
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://card-game-postgresql:5432/demo
      - APP_SLEEP=30
  card-game-postgresql:
    extends:
      file: postgresql.yml
      service: card-game-postgresql
